"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.optionalToResult = exports.safe3 = exports.safe2 = exports.mapOptional = exports.maybe = exports.bind = exports.isNone = exports.isSome = exports.makeNone = exports.makeSome = void 0;
const list_1 = require("./list");
const result_1 = require("./result");
const makeSome = (value) => ({ tag: "Some", value: value });
exports.makeSome = makeSome;
const makeNone = () => ({ tag: "None" });
exports.makeNone = makeNone;
const isSome = (o) => o.tag === "Some";
exports.isSome = isSome;
const isNone = (o) => o.tag === "None";
exports.isNone = isNone;
const bind = (o, f) => exports.isSome(o) ? f(o.value) : o;
exports.bind = bind;
const maybe = (o, ifSome, ifNone) => exports.isSome(o) ? ifSome(o.value) : ifNone();
exports.maybe = maybe;
const mapOptional = (f, list) => list_1.isEmpty(list) ? exports.makeSome([]) :
    exports.bind(f(list_1.first(list)), (fa) => exports.bind(exports.mapOptional(f, list_1.rest(list)), (fas) => exports.makeSome(list_1.cons(fa, fas))));
exports.mapOptional = mapOptional;
const safe2 = (f) => (xr, yr) => exports.bind(xr, (x) => exports.bind(yr, (y) => f(x, y)));
exports.safe2 = safe2;
const safe3 = (f) => (xr, yr, zr) => exports.bind(xr, (x) => exports.bind(yr, (y) => exports.bind(zr, (z) => f(x, y, z))));
exports.safe3 = safe3;
const optionalToResult = (o, message) => exports.maybe(o, (value) => result_1.makeOk(value), () => result_1.makeFailure(message));
exports.optionalToResult = optionalToResult;
